questionservice:
  image: slidewiki/questionservice:latest-dev
  restart: on-failure:5
  expose:
    - "80"
  external_links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - DATABASE_URL=mongodb # use a url or the name, defined in the docker-compose file
    - VIRTUAL_HOST=questionservice.experimental.slidewiki.org
    - LETSENCRYPT_HOST=questionservice.experimental.slidewiki.org
    - LETSENCRYPT_EMAIL=pbaptist@uni-bonn.de
    - LETSENCRYPT_TEST=false
